# Getting and Cleaning Data - Course Project

This readme explains the `run_analysis.R` file.

1. The final loads the downloaded files into R. The directory for the test and training sets needs to be modified to reflect the location of the files.
2. The datafiles are then combined using rbind and cbind to ro and column join the files. The X,Y and Subject files are joined together from both the train and test data set into one big dataset
3. Only the data columns that have mean or std dev are kept. the rest are removed.
4. Activity Names are used instead of "1","2", etc. The names are from the activity labels file.
5. The column names are cleaned up
6. using Melt and cast the table is reshaped to give the means for each column against Subject and Activity
7. The Datasets are then saved.


1. Download the dataset if it does not already exist in the working directory
2. Load the activity and feature info
3. Loads both the training and test datasets, keeping only those columns which
   reflect a mean or standard deviation
4. Loads the activity and subject data for each dataset, and merges those
   columns with the dataset
5. Merges the two datasets
6. Converts the `activity` and `subject` columns into factors
7. Creates a tidy dataset that consists of the average (mean) value of each
   variable for each subject and activity pair.

The end result is shown in the file `tidy.txt`.